trigger.library.secret:
  variables:
    TOX_WORKSPACE: "library/secret"
  stage: trigger
  trigger:
    include: $TOX_WORKSPACE/downstream.yml  
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - .gitlab-ci.yml
        - library/.gitlab-ci.yml
        - $TOX_WORKSPACE/*
        - $TOX_WORKSPACE/**/*
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG =~ /^\d+(\.\d+)+(rc)?$/
    - if: $CI_PIPELINE_SOURCE == "web" && $LICO_RUN_SSRB
