# Generated by Django 2.2.17 on 2021-02-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_lico_template_1_0_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='runtime',
            name='type',
            field=models.CharField(default='Runtime', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='runtime',
            unique_together={('name', 'username', 'type')},
        ),
    ]
