# Generated by Django 2.2.17 on 2021-05-21 09:57

import django.db.models.deletion
from django.db import migrations, models

import lico.core.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_lico_template_1_2_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('index', models.IntegerField()),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='template.Runtime')),
            ],
            options={
                'unique_together': {('runtime', 'filename')},
            },
            bases=(models.Model, lico.core.contrib.models.ToDictMixin),
        ),
    ]
