# Generated by Django 2.2.17 on 2022-08-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('template', '0003_lico_template_1_3_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemplate',
            name='category',
            field=models.CharField(default='General', max_length=128),
        ),
        migrations.AddField(
            model_name='usertemplate',
            name='index',
            field=models.IntegerField(default=99999),
        ),
        migrations.AlterField(
            model_name='jobcomp',
            name='notice_type',
            field=models.CharField(
                choices=[
                    ('rest', 'restapi'),
                    ('email', 'email'),
                    ('lico_restapi', 'lico_restapi')
                ],
                default='rest', max_length=20),
        ),
    ]
