trigger.library.filesystem:
  variables:
    TOX_WORKSPACE: library/filesystem
    OBS_PACKAGE: lico-filesystem-client
  stage: trigger
  trigger:
    include: library/.gitlab-ci-template.yml
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - .gitlab-ci.yml
        - library/.gitlab-ci*.yml
        - $TOX_WORKSPACE/*
        - $TOX_WORKSPACE/**/*
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG =~ /^\d+(\.\d+)+(rc)?$/
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - $TOX_WORKSPACE/*
        - $TOX_WORKSPACE/**/*
    - if: $CI_PIPELINE_SOURCE == "web" && $LICO_RUN_SSRB
    - if: $CI_PIPELINE_SOURCE == "web" && $LICO_UPLOAD_PACKAGE
