trigger.daemon.confluent-proxy:
  variables:
    TOX_WORKSPACE: daemon/confluent-proxy
    OBS_PACKAGE: lico-confluent-proxy
  stage: trigger
  trigger:
    include: daemon/.gitlab-ci-template.yml  
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - .gitlab-ci.yml
        - daemon/.gitlab-ci*.yml
        - $TOX_WORKSPACE/*
        - $TOX_WORKSPACE/**/*
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG =~ /^\d+(\.\d+)+(rc)?$/
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - $TOX_WORKSPACE/*
        - $TOX_WORKSPACE/**/*
    - if: $CI_PIPELINE_SOURCE == "web" && $LICO_RUN_SSRB
